<?php

//============================================================================
//
// s-audit_config.php
// ------------------
//
// Configuration for the s-audit's web interface. Tells the other PHP
// scripts where things are. You shouldn't need to change this. User changes
// are in site_config.php.
//
// Part of s-audit. (c) 2011 SearchNet Ltd
//  see http://snltd.co.uk/s-audit for licensing and documentation
//
//============================================================================

define("ROOT", $_SERVER["DOCUMENT_ROOT"]);
	// Site root. Usually document root

define("LIB", ROOT . "/_lib");
	// path to _lib/ directory. Lots of things are in there

define("BASE_DIR", "/var/s-audit");
	// Root of /var data

define("AUDIT_DIR", BASE_DIR . "/audit");
	// Root of audit data

define("LIVE_DIR", AUDIT_DIR . "/live");
	// Directory holding live audit files

define("URI_MAP_FILE", AUDIT_DIR . "/dns/uri_list.txt");
	// Path to map file generated by s-audit_dns_resolver.sh

define("IP_LIST_FILE", AUDIT_DIR . "/ip_list/ip_list.txt");
	// Path to map file generated by s-audit_subnet.sh

define("IP_RES_FILE", AUDIT_DIR . "/ip_list/ip_list_reserved.txt");
	// Path to hand-made list of "reserved" IP addresses

define("PER_PAGE", 20);
	// How many servers to show on each page. This refers to GLOBAL zones

define("DOC_URL", "/docs");
	// URL to top of document tree

define("KEY_DIR", LIB . "/keys");
	// Keys for grids. Also used in documentation

define("CB_URL", DOC_URL . "/_files");
	// URL to code blocks and HTMLized code blocks

define("CB_DIR", ROOT . "/docs/_files");
	// Where the codeBlock class finds syntax coloured script files. (Path,
	// not URL.)

define("PKG_DEF_DIR", LIB . "/pkg_defs");
	// Where to find package definition files

define("PCH_DEF_DIR", LIB . "/pch_defs");
	// Where to find patch definition files

// We always need our basic classes

require_once(LIB . "/display_classes.php");
require_once(LIB . "/colours.php");

// And the site config

require_once(ROOT . "/_conf/site_config.php");

?>
