<?php

//============================================================================
//
// site_config.php
// ---------------
//
// Configuration for the Becta Auditor interface. Tells the other PHP
// scripts where things are.
//
// R Fisher
//
// v1.0
// Please record changes below.
//
// v1.1 New paths. All paths now relative to new BASE_DIR. Removed unused
// definitions. Fully commented. RDF 20/10/2009
//
//============================================================================

define("MY_VER", "2.5");
	// Interface software version

define("ROOT", $_SERVER["DOCUMENT_ROOT"]);
	// Site root. Usually document root

define("SITE_NAME", "s-audit");
	// Site name, displayed on all page titles

define("BASE_DIR", "/var/s-audit");
	// Root of /var data

define("AUDIT_DIR", BASE_DIR . "/audit");
	// Root of audit data

define("LIVE_DIR", AUDIT_DIR . "/live");
	// Directory holding live audit files

define("OBSOLETE_DIR", AUDIT_DIR . "/obsolete");
	// Directory holding obsolete audit files

define("TRASH_DIR", AUDIT_DIR . "/trash");
	// Directory holding "deleted" audit files

define("NB_DIR", BASE_DIR . "/nb_data");
	// Directory holding NetBackup audit data

define("URI_MAP_FILE", AUDIT_DIR . "/uri_list.txt");
	// Path to map file generated by becta_audit_resolver.sh

define("IP_LIST_FILE", AUDIT_DIR . "/ip_list.txt");
	// Path to becta_subnet_audit.sh generated IP address map

define("IP_RES_FILE", AUDIT_DIR . "/ip_list_reserved.txt");
	// Path to hand-made list of "reserved" IP addresses

define("PER_PAGE", 20);
	// How many servers to show on each page. This refers to GLOBAL zones

define("STRIP_DOMAIN", "ngfl.gov.uk");
	// If this is defined, the domain name will be stripped off the
	// hostnames on the IP listing page and NFS shares on the security page

define("ALOM_SFX", "-lom." . STRIP_DOMAIN);
	// When we try to guess ALOM IP addresses, we tag this on to the end of
	// the hostname, then do a DNS lookup

define("SHOW_SERVER_INFO", true);
	// Whether or not to expose server information in the footer

define("DOC_SCR_DIR", ROOT . "/docs/_files");
	// Where the codeBlock class finds syntax coloured script files

// We always need our basic classes

require_once(ROOT . "/_lib/display_classes.php");
require_once(ROOT . "/_lib/colours.php");
require_once(ROOT . "/_lib/key_classes.php");

?>
