<?php

include("$_SERVER[DOCUMENT_ROOT]/_conf/site_config.php");

//------------------------------------------------------------------------------
// SCRIPT STARTS HERE

$menu_entry = "platform audits";
$pg = new docPage($menu_entry);

echo "<p>The information presented by this page is generated by
<tt>s-audit.sh</tt>'s <a href=\"" . DOC_URL . "/client/" .
basename($_SERVER["PHP_SELF"]) .  "\">platform audit class</a>.";

?>

<dl>

	<dt>hostname</dt>
	<dd>The hostname of the server or zone. Global zones, which may be
	physical servers, logical domains, or virtualized environments, are
	displayed in <strong>bold</strong> face. Non-global zones are in a
	lighter face.</dd>

	<dt>hardware</dt>
	<dd>This field displays the name of the hardware. The names of SPARC
	systems are shown, whilst Intel/AMD machines are simply listed as
	&quot;i86pc&quot;. On a separate line, in parentheses, the instruction
	set architecture is displayed. That is, 32- or 64-bit, SPARC or
	x86. No information is displayed for local zones.</dd>

	<dt>virtualization</dt>
	<dd>This field explains what the system is running on. If it is a
	physical server, &quot;physical&quot; is displayed. For virtualized
	environments, the nature of that virtualization is given, which may be
	LDOM, VirtualBox or VMWare. Global zones, whatever the platform, are
	denoted by a blue border. For non-global zones, the nature of the zone
	(whole or sparse root) is listed, along with the brand, if it in not
	native. Whole root zones are outlined in red, and non-native zones are
	on an amber field.</dd>

	<dt>CPU</dt>
	<dd>Shows the number of CPUs along with their clock speed and number of
	cores. Note that for the primary domain of a machine with LDOMs, this
	will only show the number of CPUs available to that domain, not
	to the server as a whole. For VirtualBox and VMWare environments, the
	number of CPUs available to the systems is displayed - it may not have
	exclusive use of those CPUs.  No information is displayed for local
	zones.</dd>

	<dt>memory</dt>
	<dd>Shows the physical and virtual memory in an environment.
	Note that this is the total memory, not the &quot;free&quot; or
	&quot;available&quot; memory at the time of the audit.
	If a machine has no swap space, it will be highlighted by an amber
	field. In the primary domain of a machine with LDOMs, this will show the
	amount of physical RAM available to that domain, not installed in the
	server as a whole. For VirtualBox and VMWare environments, the memory
	given over to the system - it may not have exclusive use of it.  No
	information is displayed for local zones.</dd>

	<dt>serial number</dt>
	<dd>If Sun Sneep has been used to put a machine's serial number in the
	EEPROM, it will be displayed here. Blank in local zones.</dd>

	<dt>OBP</dt>
	<dd>Shows the OBP version of a SPARC server. Information is still
	displayed for x86 machines, but will be of limited value. Blank in local
	zones.</dd>

	<dt>ALOM f/w</dt>
	<dd>On supported SPARC servers, shows the version of the ALOM firmware.
	Blank in local zones.</dd>

	<dt>ALOM IP</dt>

	<dt>storage</dt>
	<dd>This field shows all storage to which a host has access. Disks are
	on a blue-grey field, grouped by size and bus type, for instance, SCSI,
	VBOX, IDE (note that SATA disks are shown as &quot;IDE&quot;), SCSI
	VHCI, SAS, etc. Optical disks are on a grey field, again grouped by bus
	type. Optical drives which have disks loaded or mounted are highlighted
	in green and amber respectively.</dd>
	
	<dd>Tape drives are shown on a red field.  Note that jukeboxes typically
	contain multiple drives, and the drives are reported, not the
	enclosures.</dd>
	
	<dd>Optical storage arrays, for instance T3s and 3510s are shown on a
	blue field. If they can be retrieved, the model name and firmware
	revision are shown. Note that the disks the array contains will be
	listed AS WELL AS the array itself.</dd>

	<dt>PCI card</dt>
	<dd>Lists PCI cards. The type of card, e.g. network, SCSI, etc, is
	shown in <strong>bold face</strong>, with roughly human-readable details
	of the card following it in parentheses. For instance, SUNW,pci-qfe
	PCI0@33MHz can be interpreted as a Sun PCI Quad Fast Ethernet card in
	PCI slot 0, which has a 33MHz bus speed.</dd>

	<dd>This information can only be reliably retrieved on SPARC systems
	running Solaris 10 or later. If you see information for older, or x86
	systems, you're lucky.</dd>

	<dt>SBUS card</dt>

	<dt>printer</dt>
	<dd>Lists any printers to which the host has access. They may or may not
	be physically attached. The default printer is denoted.</dd>

	<dt>MAC</dt>
	<dd>Lists the MAC address for each discovered interface. Blank in local
	zones, unless that zone uses a VNIC or exlusive IP instance.</dd>

	<dt>NIC</dt>
	<dd>On the left of the field are physical (in <strong>bold</strong>
	face) or virtual NIC names. For physical NICs, the speed and duplex
	setting, if they could be determined, are displayed below the name. On
	the right is the IP address assigned to that NIC, with the hostname
	assigned to it in parentheses. If a NIC is not cabled, or not
	configured, that information is displayed. In a global zone which has
	local zones under it, virtual NICs are shown in the global zone, paired
	with the zone to which they belong. They are also shown in the row
	belonging to the local zone. Exclusive IP instances are denoted.</dd>

	<dd>Crossbow VNICs are listed by name, and in a global zone, the
	physical interface to which they are bound is displayed.</dd>

	<dd>Interfaces assigned by DHCP say &quot;DHCP&quot; under their
	physical name, and IPMP teamed intefaces are also denoted.</dd>

	<dt>audit completed</dt>
	<dd>Shows the time the audit was performed. Audits more than 24 hours
	old are highlighted by an amber field, those older than a week by a red
	field.</dd>

</dl>

<?php

$pg->close_page();

?>

