<?php

include("$_SERVER[DOCUMENT_ROOT]/_conf/site_config.php");

//------------------------------------------------------------------------------
// SCRIPT STARTS HERE

$menu_entry = "tool audits";
$pg = new docPage($menu_entry);

echo "<p>The information presented by this page is generated by
<tt>s-audit.sh</tt>'s <a href=\"" . DOC_URL . "/client/" .
basename($_SERVER["PHP_SELF"]) .  "\">software tool audit class</a>.";

?>

<?php

$pg->close_page();

?>

